- name: Pre-deploy
  hosts: ruby_app
    
  tasks:
    - name: Put SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: Check if Python 3 is installed
      command: python3 --version
      ignore_errors: yes
      register: python3_installed

    - name: Install Python 3 if not installed
      package:
        name: python3
        state: present
      when: python3_installed.rc != 0
    
    - name: Set ansible_python_interpreter to Python 3
      set_fact:
        ansible_python_interpreter: /usr/bin/python3
    
    - name: Install required build tools
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3-pip
        - gcc
        - postgresql-devel
        - postgresql-libs
      tags:
        - install

    - name: Install required Python packages
      pip:
        name:
          - psycopg2
        state: present
        executable: pip3

- name: Install Postgres
  hosts: test_cent
  roles:
    - postgres

# - name: Install NGINX
#   hosts: {{ host }}
#   roles:
#     - nginx
