- name: Pre-deploy
  hosts: ruby
    
  tasks:
    - name: Put SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

    - name: Git install
      yum:
        name: git
        state: present

    - name: Check if Python 3 is installed
      command: python3 --version
      ignore_errors: true
      register: python3_installed

    - name: Install Python 3 if not installed
      package:
        name: python3
        state: present
      when: python3_installed.rc != 0

    - name: Set ansible_python_interpreter to Python 3
      set_fact:
        ansible_python_interpreter: /usr/bin/python3

    - name: Install required build tools
      yum:
        name:
        - '@development tools'
        - epel-release
        - zlib-devel
        - openssl-static
        - gcc-c++
        - patch
        - readline-devel
        - libffi-devel
        - openssl-devel
        - make
        - bzip2
        - autoconf
        - automake
        - libtool
        - bison
        - sqlite-devel
        - libxml2-devel
        - libxslt-devel
        - pkgconfig
        - postgresql-devel
        - python3-pip
        - python3-devel
        - postgresql-libs
        state: present

    - name: Install node js
      yum:
        name:
          - nodejs
        state: present

    - name: Install required Python packages
      pip:
        name:
          - psycopg2
        state: present
        executable: pip3

- name: Install Postgres
  hosts: ruby
  roles:
    - postgres

- name: Install APP
  vars_files:
    - slurm_secrets.yml
  hosts: ruby
  roles:
    - xpaste

- name: Install NGINX
  hosts: ruby
  roles:
    - ansible-role-nginx
